[package]
name = "cards"
version = "0.1.0"
authors = ["Luke Titley <from+badja@luketitley.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.10.0"
